// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 会话活动状态。
 */
export type ActivityState = "starting" | "idle" | "working" | "waiting_user" | "disconnected" | "failed";
