// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Absolute, canonical path of an agent.
 *
 * Wire representation is a string. Deserialization always revalidates the
 * grammar, so malformed paths cannot enter canonical facts through JSON.
 */
export type AgentPath = string;
