// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ask_user 表单中的单个答案。
 */
export type AskAnswer = { question_id: string, answer: string, };
