// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ask_user 中的单个问题。
 */
export type AskQuestion = { 
/**
 * 本 ask 内唯一（如 "q1"）。
 */
id: string, 
/**
 * 问题文本（支持 Markdown）。
 */
question: string, 
/**
 * 预设选项；空 = 仅自由文本。
 */
options?: Array<string>, 
/**
 * 是否允许自定义输入。
 */
allow_custom: boolean, };
