// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentHash } from "./ContentHash";

export type AuditRef = { audit_seq: number, audit_hash: ContentHash, };
