// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 客户端 open 请求。
 */
export type ClientOpenRequest = { schema: string, version: number, 
/**
 * 客户端实例 id（后续 lease 绑定该身份）。
 */
client_instance_id: string, };
