// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 服务端 open 响应。
 */
export type ClientOpenResponse = { schema: string, version: number, accepted: boolean, 
/**
 * 服务端签发的 client session id（lease 与命令绑定该身份）。
 */
client_session_id: string, 
/**
 * 服务端 epoch（SSE stream_seq 基准）。
 */
server_epoch: string, 
/**
 * 逻辑 lease 的 TTL（毫秒）。
 */
lease_ttl_ms: number, 
/**
 * 建议的 lease renew 间隔（毫秒，< TTL）。
 */
renew_interval_ms: number, };
