// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * compact 终态（PLAN：completed/skipped/failed/cancelled 明确状态）。
 */
export type CompactStatus = "completed" | "skipped" | "failed" | "cancelled";
