// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Context compaction terminal status. Wire values mirror
 * `qaqh_domain::CompactStatus`; declared here because the v2 delta vocabulary
 * is self-contained and carries the TS export.
 */
export type CompactStatus = "completed" | "skipped" | "failed" | "cancelled";
