// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LspDto } from "./LspDto";
import type { McpDto } from "./McpDto";
import type { SubagentDto } from "./SubagentDto";

/**
 * 读模型：daemon `config.load` 的完整投影。所有消费者（设置页/Info 面板/
 * TUI/web）从这里取值；不做向前兼容——缺字段即解析失败（见 crate 级兼容策略）。
 */
export type ConfigDto = { model: string, 
/**
 * BYOK 的 endpoint：scheme + host + 可选前缀（不含 wire 自身路径）。
 */
baseUrl: string, 
/**
 * 该 endpoint 说的 wire：`openai` | `responses` | `anthropic`。
 */
wire: string, maxTokens: number, 
/**
 * 端点声明的上下文窗口——本地压缩的唯一分母（软阈值与硬 pre-flight 同源）。
 */
contextLength: number, reasoningEffort: string, autoCompactThreshold: number, permissionLevel: number, 
/**
 * 密钥永不出 daemon：空串 = 未配置、`"****"` = 已配置（掩码）。
 */
apiKey: string, lang: string | null, fontFamily: string, 
/**
 * None/空 = 跟随系统。
 */
theme: string | null, 
/**
 * 语义缺省（开）由**产出侧**决定：`qaqh-config/src/dto.rs::to_dto` 里
 * `unwrap_or(true)`。读侧不再兜底——见 `dto_rejects_a_partial_payload`。
 */
notificationsEnabled: boolean, activeProfile: string, 
/**
 * profile 名列表（管理 UI 用；不含敏感字段）。
 */
profiles: Array<string>, complianceEnabled: boolean, subagent: SubagentDto, 
/**
 * MCP 客户端配置（Phase 1 只读；写模型随 workspace 隔离权限重构另立）。
 */
mcp: McpDto, 
/**
 * LSP 客户端配置（M1 只读；写模型另立）。
 */
lsp: LspDto, tokenizerPath: string | null, };
