// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LspDto } from "./LspDto";
import type { McpDto } from "./McpDto";
import type { ProviderDto } from "./ProviderDto";
import type { SubagentDto } from "./SubagentDto";

/**
 * 读模型：daemon `config.load` 的完整投影。所有消费者（设置页/Info 面板/
 * TUI/web）从这里取值；`serde(default)` 保证旧 daemon 缺字段时向前兼容。
 */
export type ConfigDto = { model: string, baseUrl: string, providerId: string, endpoint: string, maxTokens: number, contextLimit: number, reasoningEffort: string, autoCompactThreshold: number, permissionLevel: number, 
/**
 * 密钥永不出 daemon：空串 = 未配置、`"****"` = 已配置（掩码）。
 */
apiKey: string, lang: string | null, fontFamily: string, 
/**
 * None/空 = 跟随系统。
 */
theme: string | null, 
/**
 * 语义缺省（开）由**产出侧**决定：`qaqh-config/src/dto.rs::to_dto` 里
 * `unwrap_or(true)`。读侧不再兜底——见 `dto_rejects_a_partial_payload`。
 */
notificationsEnabled: boolean, activeProfile: string, 
/**
 * profile 名列表（管理 UI 用；不含敏感字段）。
 */
profiles: Array<string>, complianceEnabled: boolean, providers: Array<ProviderDto>, subagent: SubagentDto, 
/**
 * MCP 客户端配置（Phase 1 只读；写模型随 workspace 隔离权限重构另立）。
 */
mcp: McpDto, 
/**
 * LSP 客户端配置（M1 只读；写模型另立）。
 */
lsp: LspDto, tokenizerPath: string | null, };
