// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubagentPatch } from "./SubagentPatch";

/**
 * 写模型：JSON Merge Patch（K3）。反序列化时缺失即 None = 不动；
 * 序列化时跳过 None，保证 wire 上永不出现 `"field": null`。
 *
 * 刻意**不含**：profiles 名录（服务端派生）、active_profile（切换走
 * `profile.apply`）、api_key_set（服务端派生）。BYOK 后没有 provider 目录可下发。
 * `permissionLevel` 在 patch 中受 1..=3 值域校验（BUG-2026-09-13-15；三档制 2026-10-03）。
 *
 * 特例语义冻结：`apiKey`/`subagentApiKey` 沿用既有守卫——`"****"` 或空串 =
 * 保持现值（显式删除须专用接口）；其余字符串字段 Some(空串) = 显式置空。
 */
export type ConfigPatch = { 
/**
 * 主密钥：仅用户显式输入新值时 Some；掩码 `"****"`/空串 = 保持现值。
 */
apiKey: string | null, model: string | null, baseUrl: string | null, wire: string | null, maxTokens: number | null, contextLength: number | null, reasoningEffort: string | null, 
/**
 * 值域 `[0,1]`；`0` = 关闭自动压缩。
 */
autoCompactThreshold: number | null, complianceEnabled: boolean | null, lang: string | null, fontFamily: string | null, 
/**
 * None = 不动；Some("") = 跟随系统。
 */
theme: string | null, notificationsEnabled: boolean | null, 
/**
 * 权限档位（1=read-only，2=workspace-write，
 * 3=skip-permissions：显式危险 bypass，普通工具全部自动放行）。
 *
 * BUG-2026-09-13-15：历史上该字段刻意缺席写模型，只有
 * `config.set_permission_level` 单写口；但写口校验缺失时非法档位仍能从
 * `config.save` 的裸 `permissionLevel` 载荷漏进配置。现在并入 patch 并在
 * [`Self::validate`] 中做值域校验（非法即拒绝，1..=3 之外不落盘）。
 */
permissionLevel: number | null, tokenizerPath: string | null, subagent: SubagentPatch | null, };
