// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivityState } from "./ActivityState";
import type { AgentLifecycleState } from "./AgentLifecycleState";
import type { DashboardSnapshot } from "./DashboardSnapshot";
import type { LastFailure } from "./LastFailure";
import type { PendingInteraction } from "./PendingInteraction";
import type { SessionState } from "./SessionState";

/**
 * control 频道 `state`（同样不派生 `PartialEq`，理由见 [`ConversationState`]）。
 */
export type ControlState = { session_state: SessionState | null, activity: ActivityState | null, agent_lifecycle: AgentLifecycleState | null, 
/**
 * 配置版本号（每次 `config.save` 自增）。**值本身不在此**——消费者据此重拉
 * `config.load`。
 */
config_rev: number | null, 
/**
 * 会话元数据（标题）**已变更**的事实；具体值由前端重拉 `session.list`（全量权威）。
 */
meta_changed: string | null, pending_interaction: PendingInteraction | null, last_failure: LastFailure | null, last_notice: string | null, dashboard_snapshot: DashboardSnapshot | null, };
