// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivityState } from "./ActivityState";
import type { AgentLifecycleState } from "./AgentLifecycleState";
import type { AskMode } from "./AskMode";
import type { AskQuestion } from "./AskQuestion";
import type { AskResolution } from "./AskResolution";
import type { DashboardSnapshot } from "./DashboardSnapshot";
import type { DomainError } from "./DomainError";
import type { ErrorScope } from "./ErrorScope";
import type { NoticeLevel } from "./NoticeLevel";
import type { PlanReviewItem } from "./PlanReviewItem";
import type { SessionState } from "./SessionState";
import type { SkillInfo } from "./SkillInfo";
import type { SkillRuntimeInfo } from "./SkillRuntimeInfo";

/**
 * Control 频道领域事件。
 */
export type ControlEvent = { "type": "session_state_changed", session_id: string, state: SessionState, } | number | { "type": "session_activity_changed", session_id: string, state: ActivityState, turn_id?: string | null, seq: number, updated_at: number, } | { "type": "session_meta_changed", session_id: string, title?: string | null, } | { "type": "agent_lifecycle_changed", state: AgentLifecycleState, } | { "type": "dashboard_updated", hp_connected: boolean, session_id: string, tool_calls_total: number, tool_failures: number, current_phase: string, streaming: boolean, } | { "type": "dashboard_snapshot", snapshot: DashboardSnapshot, } | { "type": "interaction_requested", interaction_id: string, turn_id: string, mode: AskMode, questions: Array<AskQuestion>, } | { "type": "interaction_resolved", interaction_id: string, resolution: AskResolution, } | { "type": "plan_review_requested", interaction_id: string, turn_id: string, plan_content: string, review_type: string, todo_items?: Array<PlanReviewItem> | null, } | { "type": "plan_review_resolved", interaction_id: string, approved: boolean, } | { "type": "driver_changed", 
/**
 * `None` = 席位已释放。
 */
holder?: string | null, driver_epoch: number, } | { "type": "skills_updated", available: Array<SkillInfo>, active: Array<string>, catalog_revision?: string | null, operation_revision?: number, context_epoch: number, token_budget: number, token_usage: number, runtime: Array<SkillRuntimeInfo>, diagnostics: Array<string>, } | { "type": "system_notice", notice_id: string, level: NoticeLevel, message: string, } | { "type": "subagent_status", session_id: string, name: string, state: string, } | { "type": "operation_completed", occurrence_id: string, scope: ErrorScope, operation_id?: string | null, } | { "type": "operation_failed", occurrence_id: string, scope: ErrorScope, error: DomainError, operation_id?: string | null, };
