// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContentRef = { content_id: string, media_type: string, sha256: string, truncated: boolean, };
