// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActorRef } from "./ActorRef";
import type { ContentHash } from "./ContentHash";
import type { ContentValue } from "./ContentValue";
import type { ExecutionId } from "./ExecutionId";
import type { InteractionDecision } from "./InteractionDecision";
import type { InteractionExpiryReason } from "./InteractionExpiryReason";
import type { InteractionId } from "./InteractionId";
import type { PolicyDecisionRef } from "./PolicyDecisionRef";
import type { RecoveryAction } from "./RecoveryAction";
import type { RecoveryOutcome } from "./RecoveryOutcome";
import type { RecoveryRef } from "./RecoveryRef";
import type { SessionActivityState } from "./SessionActivityState";
import type { SessionId } from "./SessionId";
import type { SessionInteractionKind } from "./SessionInteractionKind";
import type { SessionToolError } from "./SessionToolError";
import type { SideEffectClass } from "./SideEffectClass";
import type { SubagentTerminalStatus } from "./SubagentTerminalStatus";
import type { ToolCallId } from "./ToolCallId";
import type { ToolMetrics } from "./ToolMetrics";
import type { ToolReplayCapability } from "./ToolReplayCapability";
import type { ToolTerminalStatus } from "./ToolTerminalStatus";
import type { TurnId } from "./TurnId";

export type ControlDelta = { "kind": "session_created", "data": { revision: number, session_id: SessionId, cwd: string, model: string, schema_caps: Array<string>, } } | { "kind": "round", "data": { revision: number, turn_id: TurnId, round: number, request_hash: ContentHash, context_revision: number, } } | { "kind": "activity", "data": { revision: number, turn_id: TurnId | null, call_id: ToolCallId | null, state: SessionActivityState, } } | { "kind": "tool_intent", "data": { revision: number, call_id: ToolCallId, execution_id: ExecutionId, policy_decision: PolicyDecisionRef, replay_capability: ToolReplayCapability, side_effect_class: SideEffectClass, intent_at_ms: number, } } | { "kind": "tool_finished", "data": { revision: number, call_id: ToolCallId, execution_id: ExecutionId | null, terminal_status: ToolTerminalStatus, output: ContentValue | null, error: SessionToolError | null, metrics: ToolMetrics, reconciled: boolean, } } | { "kind": "interaction_requested", "data": { revision: number, interaction_id: InteractionId, call_id: ToolCallId | null, kind: SessionInteractionKind, request: ContentValue, expires_at_ms: number | null, } } | { "kind": "interaction_resolved", "data": { revision: number, interaction_id: InteractionId, decision: ContentValue, 
/**
 * Structured verdict; `None` for legacy facts.
 */
verdict?: InteractionDecision | null, resolved_by: ActorRef, resolution_seq: number, } } | { "kind": "interaction_expired", "data": { revision: number, interaction_id: InteractionId, reason: InteractionExpiryReason, } } | { "kind": "driver_changed", "data": { revision: number, holder?: string | null, driver_epoch: number, } } | { "kind": "session_recovered", "data": { revision: number, outcome: RecoveryOutcome, recovery_ref: RecoveryRef, actions: Array<RecoveryAction>, } } | { "kind": "subagent_spawned", "data": { revision: number, child_session_id: SessionId, parent_call_id: ToolCallId, role: string | null, } } | { "kind": "subagent_finished", "data": { revision: number, child_session_id: SessionId, parent_call_id: ToolCallId, status: SubagentTerminalStatus, result: ContentValue | null, } };
