// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentUnavailable } from "./ContentUnavailable";
import type { SessionContentRef } from "./SessionContentRef";

export type ContentValue = { "kind": "inline", "data": { text: string, } } | { "kind": "ref", "data": { content_ref: SessionContentRef, } } | { "kind": "unavailable", "data": ContentUnavailable };
