// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentUnavailableReason } from "./ContentUnavailableReason";
import type { SessionContentRef } from "./SessionContentRef";

export type ContentUnavailable = { content_ref: SessionContentRef, reason: ContentUnavailableReason, observed_at_logical_ms: number, source_fact_seq: number | null, gc_event_seq: number | null, };
