// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompactStatus } from "./CompactStatus";
import type { ContentRef } from "./ContentRef";
import type { DomainError } from "./DomainError";
import type { ProviderToolState } from "./ProviderToolState";
import type { RoundDeltaKind } from "./RoundDeltaKind";
import type { UsageInfo } from "./UsageInfo";

/**
 * Conversation 频道领域事件。
 */
export type ConversationEvent = { "type": "turn_started", turn_id: string, user_text: string, } | { "type": "turn_completed", turn_id: string, stop_reason?: string | null, usage?: UsageInfo | null, } | { "type": "turn_failed", turn_id: string, error: DomainError, } | { "type": "round_delta", turn_id: string, round_num: number, kind: RoundDeltaKind, delta: string, } | { "type": "block_checkpoint", turn_id: string, round_num: number, kind: RoundDeltaKind, text: string, char_count: number, } | { "type": "round_completed", turn_id: string, round_num: number, thinking?: string | null, answer?: string | null, output_ref?: ContentRef | null, 
/**
 * true = 本回合最后一个 round。
 */
is_final: boolean, } | { "type": "provider_retrying", turn_id: string, round_num: number, attempt: number, max_retries: number, delay_secs: number, error_message: string, } | { "type": "provider_tool_status", turn_id: string, round_num: number, 
/**
 * provider 侧 call id（如 web_search_call id），**不是** QAQ-Harness tool_call_id。
 */
call_id: string, 
/**
 * 目前固定 "web_search"，为未来 provider 内建工具预留。
 */
tool_kind: string, state: ProviderToolState, } | { "type": "usage_updated", turn_id: string, round_num: number, usage: UsageInfo, context_limit: number, model: string, } | { "type": "compact_started", compact_id: string, turns_total: number, turns_keeping: number, } | { "type": "compact_progress", compact_id: string, delta: string, } | { "type": "compact_finished", compact_id: string, status: CompactStatus, summary_chars?: number | null, turns_compacted?: number | null, turns_removed?: number | null, } | { "type": "conversation_cancelled", turn_id?: string | null, };
