// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Conversation 消息的输入用途。
 */
export type ConversationInputPurpose = "trigger_turn" | "queue_only" | "steer" | "interject";
