// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActorRef } from "./ActorRef";
import type { AssistantBlockKind } from "./AssistantBlockKind";
import type { BlockId } from "./BlockId";
import type { CheckpointId } from "./CheckpointId";
import type { ContentHash } from "./ContentHash";
import type { ContentValue } from "./ContentValue";
import type { InputId } from "./InputId";
import type { InputKind } from "./InputKind";
import type { InputPurpose } from "./InputPurpose";
import type { InterruptReason } from "./InterruptReason";
import type { RecoveryRef } from "./RecoveryRef";
import type { SessionContentRef } from "./SessionContentRef";
import type { SessionToolError } from "./SessionToolError";
import type { ToolCallId } from "./ToolCallId";
import type { ToolMetrics } from "./ToolMetrics";
import type { ToolTerminalStatus } from "./ToolTerminalStatus";
import type { TurnError } from "./TurnError";
import type { TurnId } from "./TurnId";
import type { TurnMode } from "./TurnMode";
import type { TurnTerminal } from "./TurnTerminal";
import type { UsageInfo } from "./UsageInfo";

export type ConversationDelta = { "kind": "input_accepted", "data": { revision: number, input_id: InputId, input_kind: InputKind, input_purpose: InputPurpose, content: ContentValue, attachments: Array<SessionContentRef>, actor: ActorRef, } } | { "kind": "turn_started", "data": { revision: number, turn_id: TurnId, input_id: InputId, mode: TurnMode, } } | { "kind": "assistant_block_sealed", "data": { revision: number, turn_id: TurnId, block_id: BlockId, block_kind: AssistantBlockKind, content: ContentValue, model: string, usage: UsageInfo | null, } } | { "kind": "tool_call_declared", "data": { revision: number, turn_id: TurnId, call_id: ToolCallId, tool_name: string, args: ContentValue, args_hash: ContentHash, } } | { "kind": "tool_finished", "data": { revision: number, call_id: ToolCallId, terminal_status: ToolTerminalStatus, output: ContentValue | null, error: SessionToolError | null, metrics: ToolMetrics, reconciled: boolean, } } | { "kind": "turn_finished", "data": { revision: number, turn_id: TurnId, terminal: TurnTerminal, usage: UsageInfo | null, error: TurnError | null, } } | { "kind": "turn_interrupted", "data": { revision: number, turn_id: TurnId, reason: InterruptReason, last_fact_seq: number, recovery_ref: RecoveryRef, } } | { "kind": "compaction_applied", "data": { revision: number, checkpoint_id: CheckpointId, replaces_through_fact_seq: number, summary: ContentValue, context_revision: number, } };
