// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentRef } from "./ContentRef";
import type { ConversationInputPurpose } from "./ConversationInputPurpose";
import type { ConversationMode } from "./ConversationMode";
import type { ImageBlock } from "./ImageBlock";
import type { InterAgentEnvelope } from "./InterAgentEnvelope";
import type { SubagentTerminalNotification } from "./SubagentTerminalNotification";

/**
 * Conversation 频道命令。
 */
export type ConversationCommand = { "type": "conversation_send_message", text: string, images?: Array<ImageBlock>, 
/**
 * Electron main 上传后的会话附件引用；命令中不允许出现本地路径。
 */
attachments?: Array<ContentRef> | null, 
/**
 * Stable inter-agent message identity. User/UI messages may omit it
 * and fall back to the command id.
 */
message_id?: string | null, 
/**
 * Whether this message must trigger a turn or is queue-only.
 */
input_purpose: ConversationInputPurpose, 
/**
 * 系统级注入（如子代理结果回传）：以 system 角色进入 transcript 并
 * 触发新回合，跳过用户输入专属处理（compliance guard / 技能激活 /
 * todo 模式切换）。false 时行为与普通用户消息完全一致。
 */
as_system: boolean, 
/**
 * Canonical inter-agent communication metadata. When present, the
 * target session writes `InterAgentCommunication` before
 * `InputAccepted`.
 */
inter_agent?: InterAgentEnvelope | null, 
/**
 * Structured terminal fact to append before a subagent result is
 * injected. This is not parsed from message text.
 */
subagent_terminal?: SubagentTerminalNotification | null, } | { "type": "conversation_cancel", turn_id?: string | null, } | { "type": "conversation_undo_turn", turn_id: string, } | { "type": "conversation_compact", turn_id?: string | null, } | { "type": "conversation_load_more", before_turn_id: string, count: number, } | { "type": "conversation_set_mode", mode: ConversationMode, };
