// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 会话工作模式（legacy `SetMode` 语义）。
 * 只有 Plan / Code 两个有效模式；`Code` 是默认值（旧值 `normal` 兼容反序列化）。
 */
export type ConversationMode = "plan" | "code";
