// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LastRound } from "./LastRound";
import type { TurnData } from "./TurnData";
import type { UsageInfo } from "./UsageInfo";

/**
 * conversation 频道 `state`。
 *
 * 不派生 `PartialEq`：含 `TurnData` / `UsageInfo`，二者未派生该 trait；本类型是
 * DTO，消费侧不需要相等比较，故不为它去改动共享类型。
 */
export type ConversationState = { 
/**
 * 完整对话回合投影（与 `RoundData` 逐字段同构）。
 */
turns: Array<TurnData>, 
/**
 * 会话**持久化的真实回合数**（与 `turns.len()` 未必相等：快照窗口可能被裁剪）。
 */
total_turns: number, 
/**
 * 快照窗口是否还有更早的回合未交付。
 */
has_more: boolean, usage: UsageInfo | null, usage_totals: UsageInfo | null, usage_requests: number | null, cache_reported_requests: number | null, model: string | null, context_limit: number | null, 
/**
 * 当前进行中的回合 id；`None` = 无进行中回合。
 * `TurnStarted` 置位，`TurnCompleted` / `TurnFailed` / `ConversationCancelled` 清空。
 */
active_turn: string | null, last_completed_turn: string | null, last_failed_turn: string | null, 
/**
 * 最近完成的 round 摘要。
 */
last_round: LastRound | null, 
/**
 * 压缩状态（`CompactStarted` → `"running"`，`CompactFinished` → 终态字符串）。
 */
compact_status: string | null, compact_id: string | null, 
/**
 * 最近一次取消标记；**新回合开始时清空**（R6：否则快照在会话余生持续误报）。
 */
cancelled: boolean | null, };
