// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One persisted task row for the native dashboard activity snapshot.
 */
export type DashboardTask = { id: string, subject: string, description: string, status: string, evidence?: string | null, };
