// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DashboardDocument } from "./DashboardDocument";
import type { DashboardTask } from "./DashboardTask";

/**
 * Replaceable dashboard/activity payload. It is deliberately separate from
 * the transcript and is sufficient for the Electron dashboard without an
 * `Agent2Ui::Dashboard` projection.
 */
export type DashboardSnapshot = { session_id: string, documents: Array<DashboardDocument>, recent_edits: Array<string>, tasks: Array<DashboardTask>, current_todo_id?: string | null, };
