// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A document visible in the dashboard. This intentionally mirrors only the
 * renderer-facing tracking state, not the legacy protocol type.
 */
export type DashboardDocument = { tag: string, path: string, turns_since_read: number, is_stale: boolean, };
