// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 事件的可靠性等级。由**领域事件定义**显式声明（PLAN 硬规则：
 * "可靠性由事件定义显式声明；Wire 不决定业务可靠性"）。
 */
export type Delivery = "reliable" | "replaceable" | "ephemeral";
