// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlCommand } from "./ControlCommand";
import type { ConversationCommand } from "./ConversationCommand";
import type { ToolCommand } from "./ToolCommand";

/**
 * 统一领域命令入口。`channel()` 决定命令进入哪个 actor/router。
 */
export type DomainCommand = { "channel": "control" } & ControlCommand | { "channel": "conversation" } & ConversationCommand | { "channel": "tool" } & ToolCommand;
