// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlEvent } from "./ControlEvent";
import type { ConversationEvent } from "./ConversationEvent";
import type { ToolEvent } from "./ToolEvent";

/**
 * 统一领域事件。`channel()` 决定进入哪个频道 router。
 */
export type DomainEvent = { "channel": "control" } & ControlEvent | { "channel": "conversation" } & ConversationEvent | { "channel": "tool" } & ToolEvent;
