// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EndpointDto = { id: string, display: string, protocol: string, baseUrl: string, defaultModel: string, models: Array<string>, stateful: boolean, beta: boolean, };
