// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 错误归属域（用于 OperationFailed 的 scope 字段）。
 */
export type ErrorScope = "control" | "conversation" | "tool" | "system";
