// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * exec 工具默认执行配置（读模型）。
 */
export type ExecDto = { 
/**
 * `None` / 空 / "auto" = 平台优先级自动探测。
 */
defaultShell: string | null, };
