// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * exec 工具默认执行配置（写模型），嵌套于 [`ConfigPatch::exec`]。
 */
export type ExecPatch = { 
/**
 * 空串 / "auto" = 平台自动探测；其它值 = 指定默认 shell。
 */
defaultShell: string | null, };
