// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * File metadata snapshot for rich rendering.
 */
export type FileSnapshotInfo = { path: string, lines: number, size_bytes: number, start_line: number | null, end_line: number | null, tag: string | null, };
