// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 用户消息中的图片附件（multimodal）。
 */
export type ImageBlock = { 
/**
 * MIME type（如 "image/png"）。
 */
mime_type: string, 
/**
 * Base64 编码的图像数据（不含 data URI 前缀）。
 */
data: string, };
