// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InterAgentDelivery } from "./InterAgentDelivery";

/**
 * Wire-safe inter-agent communication metadata attached to a conversation
 * message. Canonical content is the command's `text`.
 */
export type InterAgentEnvelope = { message_id: string, root_session_id: string, author: string, recipient: string, other_recipients?: Array<string>, task_id?: string | null, reply_to?: string | null, causation_id?: string | null, delivery: InterAgentDelivery, created_at_ms: number, };
