// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentPath } from "./AgentPath";
import type { EventId } from "./EventId";
import type { InterAgentContent } from "./InterAgentContent";
import type { MessageId } from "./MessageId";
import type { SessionId } from "./SessionId";
import type { SessionInterAgentDelivery } from "./SessionInterAgentDelivery";

export type InterAgentCommunication = { message_id: MessageId, root_session_id: SessionId, author: AgentPath, recipient: AgentPath, other_recipients?: Array<AgentPath>, task_id?: string | null, content: InterAgentContent, reply_to?: MessageId | null, causation_id?: EventId | null, delivery: SessionInterAgentDelivery, created_at_ms: number, };
