// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Structured interaction verdict.
 *
 * `decision_ref` alone is a content hash, so a client (or a restarted daemon)
 * could not tell what an already-resolved interaction decided. The structured
 * value is additive: facts written before this field existed deserialize with
 * `decision = None` and keep `decision_ref` as their only record.
 */
export type InteractionDecision = "approved" | "rejected" | "answered" | "dismissed";
