// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Delivery semantics for an inter-agent communication.
 */
export type InterAgentDelivery = "queue" | "trigger" | "interrupt" | "steer" | "interject";
