// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InteractionExpiryReason = "timeout" | "session_closed" | "restart_policy" | "turn_cancelled";
