// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionContentRef } from "./SessionContentRef";

export type InterAgentContent = { "kind": "inline", "data": { text: string, } } | { "kind": "content_ref", "data": { content_ref: SessionContentRef, } };
