// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InterruptReason = "crash" | "restart" | "cancel_before_seal" | "unknown_fact";
