// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * conversation 频道 `last_round` 的载荷（`RoundCompleted` 写入）。
 */
export type LastRound = { turn_id: string, round_num: number, 
/**
 * 线上键名是 `final`（Rust 关键字），故此处改名。
 */
final: boolean, };
