// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 最近一次操作失败标记（`OperationFailed` 置位，`OperationCompleted` 清空）。
 */
export type LastFailure = { occurred: boolean, };
