// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LspServerDto } from "./LspServerDto";

/**
 * LSP 客户端配置读模型（docs/current/architecture.md）。
 */
export type LspDto = { enabled: boolean, idleShutdownSecs: number, 
/**
 * 按 server 名排序（BTreeMap → Vec，确定性 wire 顺序）。
 */
servers: Array<LspServerDto>, };
