// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 单个 LSP server 读模型。
 */
export type LspServerDto = { name: string, command: string, args: Array<string>, 
/**
 * 原样回显（值可为 `${secret:name}` 占位符；secret 本体在 secrets.toml）。
 */
env: { [key in string]: string }, extensions: Array<string>, startupTimeoutSecs: number, defaultTimeoutSecs: number, };
