// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InterAgentCommunication } from "./InterAgentCommunication";
import type { MailboxMessageState } from "./MailboxMessageState";

export type MailboxMessage = { communication: InterAgentCommunication, fact_seq: number, state: MailboxMessageState, delivered_fact_seq?: number | null, };
