// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MailboxMessage } from "./MailboxMessage";
import type { MessageId } from "./MessageId";

export type MailboxDelta = { "kind": "queued", "data": { revision: number, message: MailboxMessage, } } | { "kind": "delivered", "data": { revision: number, message_id: MessageId, delivered_fact_seq: number, } };
