// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 单个 MCP server 读模型。
 */
export type McpServerDto = { name: string, 
/**
 * "stdio" | "http"
 */
transport: string, command: string, args: Array<string>, 
/**
 * 原样回显（值可为 `${secret:name}` 占位符；secret 本体在 secrets.toml）。
 */
env: { [key in string]: string }, url: string, headers: { [key in string]: string }, 
/**
 * None = 全部暴露。
 */
tools: Array<string> | null, resourcesEnabled: boolean, defaultTimeoutSecs: number, maxConcurrentCalls: number, 
/**
 * stdio 子进程工作目录；空 = 继承 daemon 进程 cwd。
 */
cwd: string, };
