// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckpointId } from "./CheckpointId";
import type { DeleteReason } from "./DeleteReason";
import type { RecoveryOutcome } from "./RecoveryOutcome";
import type { RecoveryRef } from "./RecoveryRef";
import type { SessionId } from "./SessionId";
import type { SessionMetadataPatch } from "./SessionMetadataPatch";
import type { TitleSource } from "./TitleSource";

export type MetaDelta = { "kind": "created", "data": { revision: number, cwd: string, model: string, parent_session_id: SessionId | null, schema_caps: Array<string>, } } | { "kind": "metadata_changed", "data": { revision: number, patch: SessionMetadataPatch, } } | { "kind": "title_changed", "data": { revision: number, title: string, source: TitleSource, } } | { "kind": "deleted", "data": { revision: number, tombstone_at_ms: number, reason: DeleteReason, purge_after_ms: number | null, } } | { "kind": "context_revision", "data": { revision: number, checkpoint_id: CheckpointId, context_revision: number, } } | { "kind": "recovered", "data": { revision: number, outcome: RecoveryOutcome, recovery_ref: RecoveryRef, } };
