// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InteractionKind } from "./InteractionKind";

/**
 * 挂起交互（`InteractionRequested` / `PlanReviewRequested` 写入）。
 */
export type PendingInteraction = { id: string, kind: InteractionKind, };
