// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 工具权限分类（legacy `category: "read"|"write"|"exec"|"net"`）。
 */
export type PermissionCategory = "read" | "write" | "exec" | "net";
