// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionContentRef } from "./SessionContentRef";
import type { ToolIntentPolicyOutcome } from "./ToolIntentPolicyOutcome";

export type PolicyDecisionRef = { outcome: ToolIntentPolicyOutcome, rule_id: string, decided_at_ms: number, reason_ref?: SessionContentRef | null, };
