// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventId } from "./EventId";
import type { ProjectionPayload } from "./ProjectionPayload";
import type { ProjectionSlot } from "./ProjectionSlot";
import type { SessionDelivery } from "./SessionDelivery";
import type { StreamKey } from "./StreamKey";

export type ProjectionEvent = { event_id: EventId, source_fact_seq: number, source_event_id: EventId, 
/**
 * Causal source copied from the canonical fact (for example a command id).
 */
causation_id?: EventId | null, 
/**
 * Wall-clock commit time of the source fact (C3). Synthetic events with
 * no source fact (ephemeral team overlays) carry `None`.
 */
ts_ms?: number | null, stream_key: StreamKey, delivery: SessionDelivery, 
/**
 * Reliable must be `Some` and match the delivery cursor's slot.
 */
projection_slot: ProjectionSlot | null, 
/**
 * Reliable must be `Some` and equal the delivery cursor's index.
 */
projection_index: number | null, payload: ProjectionPayload, };
