// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EndpointDto } from "./EndpointDto";

/**
 * provider 目录项（endpoint 预设树）。
 */
export type ProviderDto = { id: string, display: string, endpoints: Array<EndpointDto>, };
