// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * provider 内建/服务端工具状态（决策记录 Q3 定稿：封闭枚举，禁止自由字符串）。
 */
export type ProviderToolState = "in_progress" | "searching" | "completed";
