// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentHash } from "./ContentHash";
import type { EventId } from "./EventId";
import type { RecoveryId } from "./RecoveryId";

export type RecoveryRef = { recovery_id: RecoveryId, recovery_event_id: EventId, recovery_input_fingerprint: ContentHash, };
