// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentHash } from "./ContentHash";
import type { EventId } from "./EventId";
import type { InputId } from "./InputId";
import type { InteractionExpiryReason } from "./InteractionExpiryReason";
import type { InteractionId } from "./InteractionId";
import type { LogId } from "./LogId";
import type { ProjectionSlot } from "./ProjectionSlot";
import type { RecoveryId } from "./RecoveryId";
import type { RecoveryRef } from "./RecoveryRef";
import type { RecoveryToolCompletion } from "./RecoveryToolCompletion";
import type { SessionContentRef } from "./SessionContentRef";
import type { SessionId } from "./SessionId";
import type { SubagentTerminalStatus } from "./SubagentTerminalStatus";
import type { ToolCallId } from "./ToolCallId";
import type { TurnId } from "./TurnId";
import type { TurnMode } from "./TurnMode";

export type RecoveryAction = { "kind": "turn_interrupted", turn_id: TurnId, last_fact_seq: number, } | { "kind": "turn_started", turn_id: TurnId, input_id: InputId, mode: TurnMode, recovery_ref: RecoveryRef, } | { "kind": "tool_finished", completion: RecoveryToolCompletion, } | { "kind": "interaction_expired", interaction_id: InteractionId, reason: InteractionExpiryReason, } | { "kind": "subagent_finished", child_session_id: SessionId, child_log_id: LogId, terminal_fact_seq: number, terminal_event_id: EventId, parent_call_id: ToolCallId, status: SubagentTerminalStatus, result_ref?: SessionContentRef | null, finished_at_ms: number, recovery_ref: RecoveryRef, } | { "kind": "upgrade_superseded", previous_recovery_id: RecoveryId, } | { "kind": "commit_repaired", previous_commit_generation: number, committed_fact_seq: number, committed_offset: number, } | { "kind": "move_torn_tail", from: string, to: string, bytes: number, bytes_hash: ContentHash, } | { "kind": "projection_rebuilt", projection: ProjectionSlot, through_fact_seq: number, };
