// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventId } from "./EventId";
import type { ExecutionId } from "./ExecutionId";
import type { RecoveryRef } from "./RecoveryRef";
import type { SessionContentRef } from "./SessionContentRef";
import type { SessionToolError } from "./SessionToolError";
import type { ToolCallId } from "./ToolCallId";
import type { ToolMetrics } from "./ToolMetrics";
import type { ToolTerminalStatus } from "./ToolTerminalStatus";

export type RecoveryToolCompletion = { call_id: ToolCallId, execution_id?: ExecutionId | null, terminal_status: ToolTerminalStatus, output_ref?: SessionContentRef | null, error?: SessionToolError | null, metrics: ToolMetrics, reconciled: boolean, recovery_ref: RecoveryRef, finished_at_ms: number, evidence_ref?: SessionContentRef | null, evidence_fact_seq?: number | null, evidence_event_id?: EventId | null, };
