// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecoveryOutcome = "writable" | "commit_recovery_required" | "read_only_upgrade_required" | "tombstone";
