// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogId } from "./LogId";

export type ReliableCursor = { log_id: LogId, fact_seq: number, 
/**
 * `0..=65534` is a reliable projection; `65535` is reserved for snapshot
 * `END_OF_FACT`.
 */
projection_index: number, };
