// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ResetReason = "cursor_expired" | "log_id_mismatch" | "unknown_fact" | "upgrade_required" | "replay_overflow" | "epoch_mismatch" | "cross_session" | "snapshot_missing" | "snapshot_expired" | "snapshot_hash_mismatch" | "stale_writer" | "content_quota_exceeded" | "per_connection_overflow" | "progress_buffer_overflow" | "actor_mailbox_overflow";
