// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogId } from "./LogId";
import type { ReliableCursor } from "./ReliableCursor";
import type { ResetReason } from "./ResetReason";

export type ResetRequired = { log_id: LogId, snapshot_cursor: ReliableCursor | null, reason: ResetReason, };
