// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentValue } from "./ContentValue";
import type { ResourceId } from "./ResourceId";
import type { ResourceKind } from "./ResourceKind";
import type { SessionId } from "./SessionId";
import type { SubagentTerminalStatus } from "./SubagentTerminalStatus";
import type { ToolCallId } from "./ToolCallId";

export type ResourceDelta = { "kind": "workspace_resource_changed", "data": { revision: number, resource_kind: ResourceKind, resource_id: ResourceId, source_call_id: ToolCallId | null, summary: ContentValue, deleted: boolean, } } | { "kind": "graph_edge", "data": { revision: number, child_session_id: SessionId, parent_call_id: ToolCallId, status: SubagentTerminalStatus | null, } };
