// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 命令确认：accepted 仅代表校验通过并进入正确 actor/worker，
 * 业务完成必须通过 `causation_id = command_id` 的可靠事件返回。
 */
export type RingingCommandAckStatus = "accepted" | "rejected";
