// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ringing 协议族的频道。
 *
 * 每个频道拥有独立的可靠事件流、snapshot、cursor 与消费预算
 * （Control / Conversation / Tool 物理隔离）。
 */
export type RingingChannel = "control" | "conversation" | "tool";
