// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlCommand } from "./ControlCommand";
import type { ConversationCommand } from "./ConversationCommand";
import type { ToolCommand } from "./ToolCommand";

/**
 * 统一 Ringing 命令（envelope `command` 字段）。
 */
export type RingingCommand = { "channel": "control" } & ControlCommand | { "channel": "conversation" } & ConversationCommand | { "channel": "tool" } & ToolCommand;
