// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RingingCommandState } from "./RingingCommandState";

export type RingingCommandStatus = { command_id: string, state: RingingCommandState, payload_fingerprint: string, terminal_event_id?: string | null, error_code?: string | null, };
