// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 可持久化的命令执行状态。ACK 丢失时客户端用原 command_id 查询它。
 */
export type RingingCommandState = "accepted" | "running" | "succeeded" | "failed" | "rejected";
