// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RingingCommandAckStatus } from "./RingingCommandAckStatus";

export type RingingCommandAck = { command_id: string, status: RingingCommandAckStatus, 
/**
 * 稳定错误码（rejected 时）。
 */
code?: string | null, message?: string | null, 
/**
 * 限流/退避提示（rejected 时）。
 */
retry_after_ms?: number, };
