// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlEvent } from "./ControlEvent";
import type { ConversationEvent } from "./ConversationEvent";
import type { ToolEvent } from "./ToolEvent";

/**
 * 统一 Ringing 事件（envelope `event` 字段）。
 */
export type RingingEvent = { "channel": "control" } & ControlEvent | { "channel": "conversation" } & ConversationEvent | { "channel": "tool" } & ToolEvent;
