// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { RingingChannel } from "./RingingChannel";

/**
 * 频道领域快照。**必须表达领域状态，禁止用事件数组模拟状态**
 * （PLAN 硬规则）。`state` 为对应频道的领域快照 payload
 * （Conversation/Tool/Control snapshot projection 在 transport 层注入强类型）。
 */
export type RingingChannelSnapshot = { schema: string, version: number, channel: RingingChannel, session_id: string, 
/**
 * 快照覆盖到的 stream_seq 基线（其后的可靠事件需从 cursor 回放）。
 */
baseline_stream_seq: number, state_revision: number, snapshot_version: number, state: JsonValue, };
