// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * RoundDelta 的流式块种类（决策记录 Q2：保留 kind 作 replaceable 合并键）。
 */
export type RoundDeltaKind = "thinking" | "tool_calling" | "answering";
