// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolCallDef } from "./ToolCallDef";

/**
 * One block in a round, preserving the LLM's output order.
 *
 * Blocks are streamed to the frontend in order so it can reconstruct
 * the exact sequence of reasoning → text → tool calls from the model.
 */
export type RoundBlock = { "type": "reasoning", content: string, } | { "type": "text", content: string, } | { "type": "tool", card: ToolCallDef, } | { "type": "web_search", action: string, };
