// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoundBlock } from "./RoundBlock";
import type { ToolCallDef } from "./ToolCallDef";
import type { ToolResultDef } from "./ToolResultDef";

/**
 * One round of a turn (one API call).
 */
export type RoundData = { round_num: number, is_final: boolean, thinking: string | null, answer: string | null, tool_calls: Array<ToolCallDef>, tool_results: Array<ToolResultDef>, 
/**
 * Ordered blocks preserving the LLM's output sequence (reasoning ↔ text ↔ tool).
 */
blocks: Array<RoundBlock>, };
