// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 进行中的工具（`ToolStarted` 写入，`ToolFinished` 清空）。
 */
export type RunningTool = { tool_call_id: string, turn_id: string, round_num: number, };
