// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionContentRef } from "./SessionContentRef";

export type SessionToolError = { code: string, message: string, retryable: boolean, details_ref?: SessionContentRef | null, };
