// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 会话生命周期状态。
 */
export type SessionState = "created" | "resumed" | "closed" | "archived" | "unarchived" | "deleted";
