// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchVisibility } from "./SearchVisibility";
import type { SessionId } from "./SessionId";

export type SessionMetadataPatch = { cwd?: string | null, model?: string | null, archived?: boolean | null, search_visibility?: SearchVisibility | null, parent_session_id?: SessionId | null, schema_caps?: Array<string> | null, };
