// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `session.list` / `session.meta` 条目的**统一运行状态词表**（前端契约 **G2**）。
 *
 * 2026-10-06 归一裁决：废除「worker 进程存在性」（旧 `running: bool`）语义，
 * 会话当前状态一律用 agentloop 状态表达。权威来源是 **canonical fact 投影**
 * （control 频道 activity + 挂起交互 + conversation 最近回合终态）——它从
 * 持久 fact 重放，daemon 重启后可重建；live tracker 只作投影不可读时的退路。
 *
 * 驻留语义：`canceled` / `error` 是**最近一个回合的终态**，驻留到下一回合
 * 开始（`TurnStarted` 后进入 `working`）；`idle` 表示 loop 空闲等待输入。
 */
export type SessionRunStatus = "not_running" | "idle" | "working" | "waiting_permission" | "waiting_ask" | "waiting_plan" | "canceled" | "error";
