// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReliableCursor } from "./ReliableCursor";

export type SessionDelivery = { "Reliable": { cursor: ReliableCursor, } } | { "Replaceable": { revision: number, } } | "Ephemeral";
