// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * skill 目录条目。
 */
export type SkillInfo = { name: string, description: string, 
/**
 * "project" | "user"
 */
scope: string, 
/**
 * 相对 workspace 的展示路径。
 */
source: string, };
