// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillInfo } from "./SkillInfo";
import type { SkillRuntimeInfo } from "./SkillRuntimeInfo";

/**
 * 技能面板全量状态（frontend skills panel 展示）。
 */
export type SkillsStatus = { 
/**
 * 全部可发现技能。
 */
available: Array<SkillInfo>, 
/**
 * 当前已加载（显式 / $ 提及激活）的技能名。
 */
active: Array<string>, catalog_revision: string, context_epoch: number, operation_revision: number, token_budget: number, token_usage: number, runtime: Array<SkillRuntimeInfo>, diagnostics: Array<string>, };
