// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * skill 运行时条目（catalog/requested/active/unavailable 生命周期状态）。
 */
export type SkillRuntimeInfo = { name: string, description: string, 
/**
 * 生命周期状态：\"catalog\" | \"requested\" | \"active\" | \"unavailable\"。
 */
state: string, 
/**
 * 展示源路径。
 */
source: string, 
/**
 * skill 正文估算 token 数。
 */
token_count: number, 
/**
 * 加载失败时的错误信息。
 */
error?: string | null, };
