// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceId } from "./ResourceId";
import type { ResourceKind } from "./ResourceKind";
import type { RingingChannel } from "./RingingChannel";

export type StreamKey = { "kind": "channel", "data": RingingChannel } | { "kind": "resource", "data": { kind: ResourceKind, id: ResourceId, } };
