// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 子代理配置段（读模型）。api_key 语义同顶层：空串/"****" 掩码。
 */
export type SubagentDto = { model: string, baseUrl: string, apiKey: string, apiKeySet: boolean, maxTokens: number, timeoutSecs: number, 
/**
 * 空数组 = 全部工具可用（配置语义，非缺省）。
 */
defaultTools: Array<string>, 
/**
 * Maximum subagent tree depth. Default 1.
 */
maxDepth: number, 
/**
 * Max queued messages from one sender to one recipient. 0 = unlimited.
 */
messageInFlightPerPair: number, 
/**
 * Max cumulative outbound message attempts per sender. 0 = unlimited.
 */
messageOutboundPerSender: number, };
