// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 子代理终态种类（`SubagentTerminalNotification.terminal`）。
 */
export type SubagentTerminalKind = "completed" | "failed" | "cancelled" | "timed_out";
