// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubagentTerminalKind } from "./SubagentTerminalKind";

/**
 * Structured terminal notification carried with a subagent result injection.
 */
export type SubagentTerminalNotification = { child_session_id: string, parent_call_id: string, terminal: SubagentTerminalKind, };
