// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Conversation 频道命令。
 */
export type SubagentTerminalKind = "completed" | "failed" | "cancelled" | "timed_out";
