// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 子代理配置段（读模型）。api_key 语义同顶层：空串/"****" 掩码。
 */
export type SubagentDto = { model: string, baseUrl: string, apiKey: string, apiKeySet: boolean, maxTokens: number, 
/**
 * Maximum lifetime in seconds before the subagent is killed.
 * 仅作用于模型调用的 `spawn_subagent` 工具路径（qaqh-subagent 的 collector
 * deadline）；`subagent.spawn` RPC 路径不读它。
 */
timeoutSecs: number, 
/**
 * 空数组 = 全部工具可用（配置语义，非缺省）。
 */
defaultTools: Array<string>, 
/**
 * Maximum subagent tree depth. Default 1.
 * **只在 daemon 启动时读取**（qaqh-runtime service.rs）；改动需**重启 daemon**。
 */
maxDepth: number, 
/**
 * Max queued messages from one sender to one recipient. 0 = unlimited.
 */
messageInFlightPerPair: number, 
/**
 * Max cumulative outbound message attempts per sender. 0 = unlimited.
 */
messageOutboundPerSender: number, };
