// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 子代理配置段（写模型），嵌套于 [`ConfigPatch::subagent`]。
 */
export type SubagentPatch = { model: string | null, baseUrl: string | null, apiKey: string | null, maxTokens: number | null, timeoutSecs: number | null, 
/**
 * 允许空数组（= 全部工具可用）。
 */
defaultTools: Array<string> | null, maxDepth: number | null, messageInFlightPerPair: number | null, messageOutboundPerSender: number | null, };
