// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentPath } from "./AgentPath";
import type { SessionContentRef } from "./SessionContentRef";
import type { TeamTaskArtifact } from "./TeamTaskArtifact";

export type TeamTaskSnapshot = { task_id: string, title: string, state: string, owner?: AgentPath | null, claim_epoch: number, depends_on?: Array<string>, artifacts?: Array<TeamTaskArtifact>, acceptance?: Array<string>, result_ref?: SessionContentRef | null, created_at_ms: number, updated_at_ms: number, };
