// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionContentRef } from "./SessionContentRef";

export type TeamTaskArtifact = { content_ref: SessionContentRef, media_type: string, added_at_ms: number, };
