// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TeamAgentStatus = "pending_init" | "running" | "waiting_user" | "interrupted" | "completed" | "errored" | "shutdown" | "not_found";
