// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentPath } from "./AgentPath";
import type { SessionId } from "./SessionId";
import type { TeamAgentResidency } from "./TeamAgentResidency";
import type { TeamAgentStatus } from "./TeamAgentStatus";

export type TeamAgentSnapshot = { agent_id: SessionId, agent_path: AgentPath, nickname?: string | null, role?: string | null, status: TeamAgentStatus, residency: TeamAgentResidency, parent_agent_path?: AgentPath | null, current_task_id?: string | null, };
