// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentPath } from "./AgentPath";

export type TeamBoardThread = { thread_id: string, channel_id: string, title: string, task_id?: string | null, created_by: AgentPath, created_at_ms: number, post_count: number, };
