// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionId } from "./SessionId";
import type { TeamBoardChannel } from "./TeamBoardChannel";
import type { TeamBoardPost } from "./TeamBoardPost";
import type { TeamBoardSubscription } from "./TeamBoardSubscription";
import type { TeamBoardThread } from "./TeamBoardThread";

export type TeamBoardSnapshot = { board_id?: SessionId | null, revision: number, last_fact_seq: number, channels?: Array<TeamBoardChannel>, threads?: Array<TeamBoardThread>, posts?: Array<TeamBoardPost>, subscriptions?: Array<TeamBoardSubscription>, };
