// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentPath } from "./AgentPath";

export type TeamBoardChannel = { channel_id: string, name: string, topic?: string | null, created_by: AgentPath, created_at_ms: number, };
