// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentPath } from "./AgentPath";
import type { TeamBoardSubscriptionTarget } from "./TeamBoardSubscriptionTarget";

export type TeamBoardSubscription = { target: TeamBoardSubscriptionTarget, subscriber: AgentPath, subscribed: boolean, updated_at_ms: number, };
