// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageId } from "./MessageId";
import type { SessionId } from "./SessionId";
import type { TeamAgentResidency } from "./TeamAgentResidency";
import type { TeamAgentSnapshot } from "./TeamAgentSnapshot";
import type { TeamAgentStatus } from "./TeamAgentStatus";
import type { TeamBoardSnapshot } from "./TeamBoardSnapshot";
import type { TeamInboxSummary } from "./TeamInboxSummary";
import type { TeamTaskSnapshot } from "./TeamTaskSnapshot";

export type TeamDelta = { "kind": "agent_joined", "data": { revision: number, agent: TeamAgentSnapshot, } } | { "kind": "agent_status_changed", "data": { revision: number, agent_id: SessionId, status: TeamAgentStatus, } } | { "kind": "agent_residency_changed", "data": { revision: number, agent_id: SessionId, residency: TeamAgentResidency, } } | { "kind": "agent_message_queued", "data": { revision: number, message: TeamInboxSummary, } } | { "kind": "agent_message_delivered", "data": { revision: number, message_id: MessageId, } } | { "kind": "agent_interrupted", "data": { revision: number, agent_id: SessionId, } } | { "kind": "agent_completed", "data": { revision: number, agent_id: SessionId, status: TeamAgentStatus, } } | { "kind": "task_changed", "data": { revision: number, task: TeamTaskSnapshot, } } | { "kind": "board_changed", "data": { revision: number, board: TeamBoardSnapshot, } };
