// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentPath } from "./AgentPath";
import type { MessageId } from "./MessageId";
import type { SessionInterAgentDelivery } from "./SessionInterAgentDelivery";

export type TeamInboxSummary = { message_id: MessageId, author: AgentPath, recipient: AgentPath, task_id?: string | null, delivery: SessionInterAgentDelivery, created_at_ms: number, };
