// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentPath } from "./AgentPath";

export type TeamBoardPost = { post_id: string, thread_id: string, task_id?: string | null, author: AgentPath, body: string, created_at_ms: number, reply_to?: string | null, };
