// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * State updates for a tool block; all updates retain the block's position.
 */
export type TimelineToolState = "prepared" | "running" | "succeeded" | "failed" | "cancelled" | "backgrounded";
