// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssistantBlockKind } from "./AssistantBlockKind";
import type { BlockId } from "./BlockId";
import type { CheckpointId } from "./CheckpointId";
import type { ContentValue } from "./ContentValue";
import type { InputId } from "./InputId";
import type { InterruptReason } from "./InterruptReason";
import type { SessionToolError } from "./SessionToolError";
import type { ToolCallId } from "./ToolCallId";
import type { ToolTerminalStatus } from "./ToolTerminalStatus";
import type { TurnId } from "./TurnId";
import type { TurnTerminal } from "./TurnTerminal";

export type TimelineDelta = { "kind": "input", "data": { revision: number, input_id: InputId, content: ContentValue, } } | { "kind": "block", "data": { revision: number, block_id: BlockId, block_kind: AssistantBlockKind, content: ContentValue, } } | { "kind": "tool_call", "data": { revision: number, call_id: ToolCallId, tool_name: string, args: ContentValue, } } | { "kind": "tool_result", "data": { revision: number, call_id: ToolCallId, terminal_status: ToolTerminalStatus, output: ContentValue | null, error: SessionToolError | null, } } | { "kind": "turn_finished", "data": { revision: number, turn_id: TurnId, terminal: TurnTerminal, } } | { "kind": "turn_interrupted", "data": { revision: number, turn_id: TurnId, reason: InterruptReason, } } | { "kind": "compaction", "data": { revision: number, checkpoint_id: CheckpointId, summary: ContentValue, } };
