// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimelineBlockKind } from "./TimelineBlockKind";
import type { TimelineFailure } from "./TimelineFailure";
import type { TimelineTool } from "./TimelineTool";
import type { TimelineTurnState } from "./TimelineTurnState";

/**
 * Producer-to-writer command for the native transcript. Producers never
 * allocate `timeline_seq` or a text fragment sequence: those are assigned by
 * the single writer after intents from model and tool workers have been
 * serialized onto one queue.
 *
 * This is deliberately not an `Agent2Ui` or Ringing-event wrapper. It has no
 * channel, delivery, SSE, or legacy message fields.
 */
export type TimelineIntent = { "type": "turn_opened", turn_id: string, user_text: string, } | { "type": "block_opened", turn_id: string, round_num: number, block_id: string, kind: TimelineBlockKind, tool?: TimelineTool | null, } | { "type": "text_delta", turn_id: string, round_num: number, block_id: string, delta: string, } | { "type": "block_checkpoint", turn_id: string, round_num: number, block_id: string, text: string, } | { "type": "tool_updated", turn_id: string, round_num: number, block_id: string, tool: TimelineTool, } | { "type": "tool_progress", turn_id: string, round_num: number, block_id: string, chunk: string, 
/**
 * 进度流标识（"stdout" | "stderr"）；None = 未知。
 */
stream?: string | null, 
/**
 * 累计观测字节（emitted + dropped），0 = 未接线。
 */
bytes_total?: number, } | { "type": "tool_estimated", turn_id: string, round_num: number, block_id: string, lines_added: number, lines_removed: number, } | { "type": "block_sealed", turn_id: string, round_num: number, block_id: string, } | { "type": "round_sealed", turn_id: string, round_num: number, is_final: boolean, } | { "type": "turn_sealed", turn_id: string, state: TimelineTurnState, failure?: TimelineFailure | null, };
