// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimelineFailure } from "./TimelineFailure";
import type { TimelineToolDisplay } from "./TimelineToolDisplay";
import type { TimelineToolPermission } from "./TimelineToolPermission";
import type { TimelineToolState } from "./TimelineToolState";

/**
 * Immutable identity and mutable presentation state for one tool block.
 */
export type TimelineTool = { tool_call_id: string, name: string, state: TimelineToolState, summary?: string | null, 
/**
 * Original structured arguments as supplied by the tool producer.
 */
args_json?: string | null, 
/**
 * 保留下来的工具输出片段。
 *
 * ⚠ 这不是"完整输出"，也**不是**靠 `output_ref` 补齐的：标准模式下模型
 * 文本先被 `TOOL_MODEL_MAX_CHARS`（24K 字符）封顶，而内容外置的阈值是
 * 10 MiB，二者差两个数量级——外置路径在标准模式下永远不会触发。因此
 * `output` 就是前端能拿到的全部；想看更多应让模型用更窄的参数重调工具
 * （截断标记里也是这么提示模型的），而不是期待一个 content 下载端点。
 */
output?: string | null, 
/**
 * Display-plane unified diff (file-mutation tools). Never projected to the
 * model; consumed by the transcript renderer (diff drawer / tool cards).
 */
diff?: string | null, progress?: string, 
/**
 * True once the writer discarded an older prefix of `progress`.
 */
progress_truncated?: boolean, 
/**
 * 进度流标识（09-18 契约 §5.1）："stdout" | "stderr" | "mixed"。
 */
progress_stream?: string | null, 
/**
 * 本次调用累计观测字节（emitted + dropped，含被尾部裁剪的部分）。
 */
progress_bytes_total?: number, 
/**
 * 类型化展示投影；缺失时 client 完整回退旧字段（H16）。
 */
display?: TimelineToolDisplay | null, failure?: TimelineFailure | null, permission?: TimelineToolPermission | null, 
/**
 * 工具退出码（提升为顶层槽，契约切片 2026-10-03）。由 runtime 从
 * display body 提取——client 无需拆 body/legacy JSON 即可拿到；非
 * exec 家族恒为 `None`。归档 rebuild 从同源 display 提取。
 */
exit_code?: number | null, 
/**
 * 调用完成时间（epoch ms，runtime 在终态发射时盖戳，不信工具自报）。
 * 终态前 / 旧归档为 `None`——client 对缺席**不画**，不用本地时钟兜底。
 */
completed_at_ms?: number | null, };
