// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimelineTurn } from "./TimelineTurn";

/**
 * Authoritative recovery state, not an event array.
 */
export type TimelineSnapshot = { 
/**
 * The largest timeline sequence included in `turns`.
 */
watermark: number, turns: Array<TimelineTurn>, };
