// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle of a display block. Markdown is rendered only after `Sealed`.
 */
export type TimelineBlockState = "open" | "sealed";
