// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimelinePathOp } from "./TimelinePathOp";

export type TimelineToolHeader = { "kind": "path", path: string, op: TimelinePathOp, } | { "kind": "shell", command: string, } | { "kind": "query", query: string, scope?: string | null, } | { "kind": "other", label: string, } | { "kind": "unknown" };
