// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sanitised failure information retained with a transcript terminal event.
 */
export type TimelineFailure = { code: string, message: string, };
