// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Terminal state of a transcript turn. This is distinct from block sealing:
 * a cancelled or failed turn may have valid, already-sealed Markdown blocks.
 */
export type TimelineTurnState = "running" | "completed" | "failed" | "cancelled";
