// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimelineToolBody } from "./TimelineToolBody";
import type { TimelineToolHeader } from "./TimelineToolHeader";
import type { TimelineToolMetrics } from "./TimelineToolMetrics";
import type { ToolResultDisplayOutcome } from "./ToolResultDisplayOutcome";

/**
 * 类型化展示投影（09-18 跨仓展示契约 §3.3）。
 *
 * 全部字段可选、可忽略；未知 header/body 变体解析为 `Unknown`，
 * 旧 client 不会因为新变体丢整块。
 */
export type TimelineToolDisplay = { summary?: string | null, diff?: string | null, header?: TimelineToolHeader | null, body?: TimelineToolBody | null, metrics?: TimelineToolMetrics | null, 
/**
 * 结构化终态（#336 P2）；旧 client 忽略后仍可读 summary/body。
 */
outcome?: ToolResultDisplayOutcome | null, };
