// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TimelineToolMetrics = { elapsed_ms: number, output_bytes: number, retry_count: number, effective_tool_name?: string | null, user_initiated: boolean, };
