// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimelineBlock } from "./TimelineBlock";

export type TimelineRound = { round_num: number, sealed: boolean, is_final: boolean, blocks: Array<TimelineBlock>, };
