// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimelineEvent } from "./TimelineEvent";

/**
 * A globally ordered record for one session seed.
 */
export type TimelineEntry = { 
/**
 * Strictly monotonic for one `(server epoch, seed)` across all display kinds.
 */
timeline_seq: number, turn_id: string, round_num?: number | null, event: TimelineEvent, };
