// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimelineBlockKind } from "./TimelineBlockKind";
import type { TimelineBlockState } from "./TimelineBlockState";
import type { TimelineTool } from "./TimelineTool";

/**
 * Fully materialized display block saved in timeline snapshots.
 */
export type TimelineBlock = { block_id: string, 
/**
 * Stable order within one round. It never changes when the block updates.
 */
block_order: number, kind: TimelineBlockKind, state: TimelineBlockState, text?: string, tool?: TimelineTool | null, };
