// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tool permission data belongs to the transcript tool block, while the
 * interaction request/response lifecycle stays on the native control plane.
 */
export type TimelineToolPermission = { reason: string, paths: Array<string>, category: string, level: number, risk: string, consequence: string, };
