// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentRef } from "./ContentRef";
import type { NoticeLevel } from "./NoticeLevel";
import type { PermissionCategory } from "./PermissionCategory";
import type { PermissionRisk } from "./PermissionRisk";
import type { ToolResult } from "./ToolResult";

/**
 * Tool 频道领域事件。
 */
export type ToolEvent = { "type": "tool_call_prepared", tool_call_id: string, turn_id: string, round_num: number, name: string, args_so_far: string, } | { "type": "tool_started", tool_call_id: string, turn_id: string, round_num: number, name: string, } | { "type": "tool_finished", tool_call_id: string, turn_id: string, round_num: number, result: ToolResult, } | { "type": "tool_permission_requested", tool_call_id: string, turn_id: string, round_num: number, tool_name: string, 
/**
 * Bounded, tool-specific action summary for informed approval.
 * Optional for backward compatibility with older producers.
 */
action_summary?: string | null, reason: string, paths: Array<string>, category: PermissionCategory, level: number, risk: PermissionRisk, consequence: string, } | { "type": "tool_notice", tool_call_id?: string | null, level: NoticeLevel, message: string, } | { "type": "audit_recorded", tool_name: string, result_summary: string, success: boolean, time: string, args_ref?: ContentRef | null, } | { "type": "code_changed", tool_call_id: string, turn_id: string, round_num: number, lines_added: number, lines_removed: number, files_created: number, files_deleted: number, file?: string | null, };
