// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionContentRef } from "./SessionContentRef";

export type ToolReplayCapability = { "kind": "no_replay" } | { "kind": "idempotent_replay" } | { "kind": "reconcile", probe_ref: SessionContentRef, };
