// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileSnapshotInfo } from "./FileSnapshotInfo";
import type { ToolError } from "./ToolError";
import type { ToolResultDisplay } from "./ToolResultDisplay";
import type { ToolResultMetrics } from "./ToolResultMetrics";
import type { ToolStatus } from "./ToolStatus";

/**
 * Tool execution result used in turn projections.
 */
export type ToolResultDef = { tool_call_id: string, output: string, success: boolean, 
/**
 * 工具侧五态（Ok/Error/Partial/Cancelled/Backgrounded），历史归档无此
 * 字段（serde default 兼容旧 journal）；缺失时 rebuild 按 success 二值回退。
 */
status?: ToolStatus | null, file: FileSnapshotInfo | null, 
/**
 * 运行元数据（09-18 展示契约）。历史归档缺失时为空对象。
 */
metrics?: ToolResultMetrics, 
/**
 * Canonical display projection carried by typed tool results.
 */
display?: ToolResultDisplay | null, 
/**
 * 结构化错误（rebuild 侧失败槽的单一事实源）。历史归档无此字段
 * （serde default 兼容）；缺失时 rebuild 只能从 output 首行降级。
 */
error?: ToolError | null, };
