// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { ContentRef } from "./ContentRef";
import type { ToolError } from "./ToolError";
import type { ToolImage } from "./ToolImage";
import type { ToolModelPayload } from "./ToolModelPayload";
import type { ToolResultDisplay } from "./ToolResultDisplay";
import type { ToolResultMetrics } from "./ToolResultMetrics";
import type { ToolStatus } from "./ToolStatus";

export type ToolResult = { status: ToolStatus, data: JsonValue, 
/**
 * Images to attach to the tool result message (e.g. `read_image`).
 */
images?: Array<ToolImage>, 
/**
 * 展示平面的 unified diff（文件修改类工具的原始 diff 文本）。
 *
 * ⚠ 绝不进入模型投影（`project_for_model` 不携带它）：模型看到的仍是
 * 紧凑摘要行，diff 只供 timeline/前端抽屉消费。发送方在成功路径上
 * 显式填充；缺失时默认 None（向后兼容）。
 */
diff?: string | null, 
/**
 * Canonical display projection emitted by a typed tool.
 *
 * Legacy handlers leave this `None`; the runtime then falls back to the
 * registered text projector. Typed tools use this field so header/body
 * never have to be reconstructed from `model.text`.
 */
display?: ToolResultDisplay | null, error?: ToolError | null, 
/**
 * 运行元数据（框架填充，工具实现不写）。
 */
metrics?: ToolResultMetrics, 
/**
 * 展示/模型提示行（≤ [`TOOL_SUMMARY_MAX_CHARS`]），可被工具追加。
 */
summary: string, 
/**
 * 模型可见投影（文本、截断标记、token 估算、续调参数）。
 */
model: ToolModelPayload, 
/**
 * 大输出外置引用。**仅在 NoFold 极限模式且模型文本超过
 * `CONTENT_STORE_THRESHOLD_BYTES`（10 MiB）时才会产生**——标准模式下
 * 模型文本已被 [`TOOL_MODEL_MAX_CHARS`] 封顶（≤ 约 96 KiB），永远到不了
 * 该阈值。因此它是传输保护阀，而非常规路径：前端应视为可选字段，
 * 不要指望靠它拿"完整输出"。
 */
output_ref?: ContentRef | null, };
