// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolResultDisplayOutcomeState } from "./ToolResultDisplayOutcomeState";

/**
 * 展示面终态（#336 P2）。
 *
 * 这是 `ToolOutcome` 的 wire 投影，不是第二个执行事实源：`state` 由
 * `ToolStatus` / `ToolErrorKind` 单点派生，`exit_code` / `truncated` 由工具
 * body 派生，`duration_ms` / `output_bytes` 由框架 metrics 填充。
 */
export type ToolResultDisplayOutcome = { state: ToolResultDisplayOutcomeState, exit_code?: number | null, duration_ms?: number | null, output_bytes?: number | null, truncated?: boolean | null, };
