// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An image attachment carried by a tool result.
 *
 * Stored alongside [`ToolResult`] so the message layer can append
 * `ContentBlock::Image` blocks to the resulting tool message. Never
 * serialized into the model text projection — the gate lowers images
 * to provider-native media parts at request-build time.
 */
export type ToolImage = { mime_type: string, 
/**
 * Raw base64 payload (no `data:` prefix).
 */
data: string, };
