// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ToolTerminalStatus = "succeeded" | "failed" | "partial" | "cancelled" | "timed_out" | "backgrounded" | "indeterminate" | "denied";
