// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ToolMetrics = { started_at_ms: number, finished_at_ms: number, retry_count: number, output_bytes: number, progress_bytes_total: number, };
