// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolResultDisplayBody } from "./ToolResultDisplayBody";
import type { ToolResultDisplayHeader } from "./ToolResultDisplayHeader";
import type { ToolResultDisplayOutcome } from "./ToolResultDisplayOutcome";

export type ToolResultDisplay = { summary?: string | null, diff?: string | null, header?: ToolResultDisplayHeader | null, body?: ToolResultDisplayBody | null, 
/**
 * 结构化终态。旧 client 忽略即可；新 client 不再从文本猜 `[OK]`。
 */
outcome?: ToolResultDisplayOutcome | null, };
