// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ToolResultDisplayBody = { "kind": "none" } | { "kind": "text", text: string, truncated: boolean, } | { "kind": "diff", unified: string, files: Array<string>, } | { "kind": "shell", output: string, exit_code: number | null, truncated: boolean, } | { "kind": "streams", stdout: string, stderr: string, exit_code: number | null, truncated: boolean, interleaved: boolean, } | { "kind": "subagent", name: string, session_id: string, } | { "kind": "unknown" };
