// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";

/**
 * Tool 频道命令。
 */
export type ToolCommand = { "type": "tool_invoke", tool_call_id: string, name: string, action: string, args: JsonValue, } | { "type": "tool_permission_respond", tool_call_id: string, approved: boolean, trust_folder: boolean, };
