// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolContinuation } from "./ToolContinuation";

export type ToolModelPayload = { text: string, truncated: boolean, total_tokens: number, continuation?: ToolContinuation | null, };
