// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 工具运行元数据（09-18 展示契约 §3.4 / base spec §11）。
 *
 * `elapsed_ms = None` 表示本次结果未接线 metrics（授权拒绝、历史归档等）；
 * 全空对象不序列化，旧 wire 保持不变。
 */
export type ToolResultMetrics = { elapsed_ms?: number | null, output_bytes?: number, retry_count?: number, 
/**
 * 别名/MCP 解析后的实际工具名；None = 与卡片 name 相同。
 */
effective_tool_name?: string | null, user_initiated?: boolean, };
