// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunningTool } from "./RunningTool";

/**
 * tool 频道 `state`。
 */
export type ToolState = { 
/**
 * 等待用户授权的 tool_call_id；`None` = 无挂起授权。
 */
pending_permission: string | null, last_finished: string | null, 
/**
 * 进行中的工具；`None` = 无（线协议用 `null` 表达，而非空数组）。
 */
running: Array<RunningTool> | null, };
