// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolResultDisplayPathOp } from "./ToolResultDisplayPathOp";

export type ToolResultDisplayHeader = { "kind": "path", path: string, op: ToolResultDisplayPathOp, } | { "kind": "shell", command: string, } | { "kind": "query", query: string, scope?: string | null, } | { "kind": "other", label: string, };
