// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoundData } from "./RoundData";

/**
 * One full turn (user message + all rounds).
 */
export type TurnData = { turn_id: string, user_text: string, rounds: Array<RoundData>, };
