// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Token usage information returned by the LLM API.
 *
 * Captures both standard token counts and provider-specific fields
 * like cache hit/miss and reasoning tokens.
 */
export type UsageInfo = { 
/**
 * Tokens consumed by the input (prompt + conversation history).
 */
prompt_tokens: number, 
/**
 * Tokens generated in the model's response.
 */
completion_tokens: number, 
/**
 * Sum of prompt_tokens + completion_tokens.
 */
total_tokens: number, 
/**
 * Cached prompt tokens that were served from cache (DeepSeek).
 */
prompt_cache_hit_tokens: number, 
/**
 * Prompt tokens that missed the cache and were computed fresh.
 */
prompt_cache_miss_tokens: number, 
/**
 * Tokens consumed by internal reasoning/thinking (DeepSeek R1, etc.).
 */
reasoning_tokens: number, 
/**
 * Whether the provider actually returned cache usage fields. This keeps a
 * genuine zero-percent hit rate distinct from unsupported/missing data.
 */
cache_usage_reported?: boolean | null, };
